### ISSUE TITLE
Unexpected behavior of `Change.ofTextUpsert`

### ISSUE THREAD

**Issue by arhont375** [line/centraldogma#579]
Hello, CD team!
During writing tests for classes that using CD client I found that I can't use `Change.ofTextUpsert` in case file name have `json` extension.

In example code below test will fail with some obscure exception (can find below the code).
But if I will change `CD_FILENAME = "/filename.some"` test will pass.

I find this behavior unexpected as with the `Change.ofTextUpsert` I expect to be able to manipulate text files of any format.
```kotlin
class CentralDogmaTest {
    val centralDogma = centralDogmaExtension.client()

    @Test
    fun pushConfiguration() {
        centralDogma.createProject(CD_PROJECT).join()
        centralDogma.createRepository(CD_PROJECT, CD_REPOSITORY).join()
        centralDogma
            .push(
                CD_PROJECT,
                CD_REPOSITORY,
                Revision.HEAD,
                "summary",
                Change.ofTextUpsert(CD_FILENAME, "sometext")
            ).join()
    }

    companion object {
        @RegisterExtension
        @JvmField
        val centralDogmaExtension = CentralDogmaExtension()
        
        private const val CD_PROJECT = "cd-project"
        private const val CD_REPOSITORY = "cd-repository"
        private const val CD_FILENAME = "/filename.json"
    }
}
```
Exception message:
```
com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, content-type=application/json; charset=utf-8, server=Armeria/1.5.0, date=Tue, 6 Apr 2021 06:34:40 GMT, content-length=136], {"exception":"com.linecorp.centraldogma.server.storage.StorageException","message":"failed to convert list of DiffEntry to Changes map"}
java.util.concurrent.CompletionException: com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, content-type=application/json; charset=utf-8, server=Armeria/1.5.0, date=Tue, 6 Apr 2021 06:34:40 GMT, content-length=136], {"exception":"com.linecorp.centraldogma.server.storage.StorageException","message":"failed to convert list of DiffEntry to Changes map"}
```

**Comment by ikhoon** [comment]
> I find this behavior unexpected as with the Change.ofTextUpsert I expect to be able to manipulate text files of any format.

Central Dogma provides useful features for JSON such as:
- More detailed diff using [JSON patch](http://jsonpatch.com/)
- Declartive search using [JSON path](https://github.com/json-path/JsonPath#operators)

If a file read from a Git repository, we have to guess the file type from the file extension.
Because the file is could be created by either Central Dogma's REST API or Git mirror.
Technically, the file content and name are the only information we can get from the file system of Git mirror.

If an invalid JSON file is added using `Change.ofTextUpsert()`, you will see an expected error later.
For this reason, it might be better to return 404 Bad Request with a gentle error message for the `Change.ofTextUpser()` with JSON then accept the invalid JSON file.
