### ISSUE TITLE
Should we deprecate MultipleMirrorConfig?

### ISSUE THREAD

**Issue by minwoox** [line/centraldogma#647]
We have [SingleMirrorConfig](https://github.com/line/centraldogma/blob/centraldogma-0.52.6/server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java#L216) and [MultipleMirrorConfig](https://github.com/line/centraldogma/blob/centraldogma-0.52.6/server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java#L256) for the mirroring setup.
I believe that `MultipleMirrorConfig` is currently not used because it's not documented on our web and a user can configure multiple mirroring setups using multiple `SingleMirrorConfig`.
I'm wondering if we need to deprecate `MultipleMirrorConfig` to reduce the complexity of the module.

**Comment by ikhoon** [comment]
It seems no one uses `MultipleMirrorConfig` since the documentation says to use `single`.

Additionally, I found it difficult to update a mirror configuration with REST API while implementing the mirror UI with the current data format. #50 There is no unique ID in a mirror configuration. As a result, an update request should use the index in the array at `mirrors.json`.

If `MultipleMirrorConfig` is considered, the UI and index lookup could be complex for the unused feature. Let me move `MultipleMirrorConfig` in the mirroring UI issue together.

**Comment by ikhoon** [comment]
Resolved by #838
